// dataAcara.js
export const acaraList = [
  {
    id: 1,
    title: "Acara Hijau Hutan Bogor",
    status: "Sedang Berlangsung",
    time: "07.00–10.00 WIB",
    desc: "Kegiatan penanaman bibit pohon di Hutan Kota Bogor bersama relawan dan komunitas hijau. Tujuannya adalah memperluas area hijau dan menjaga kelestarian ekosistem.",
    image: "/acara1.jpg",
    location: "Hutan Kota Bogor",
    gallery: ["/acara1.jpg", "/acara2.jpg", "/acara3.jpg"],
    team: [
      { name: "Aghis Sulaiman", role: "Koordinator Lapangan" },
      { name: "Shyfa Nuraini", role: "Ketua Panitia" },
      { name: "Rafi Pratama", role: "Dokumentasi" },
    ],
    benefits: [
      "Meningkatkan area hijau di sekitar Bogor.",
      "Mendukung program penghijauan nasional.",
      "Menambah kesadaran pentingnya menjaga hutan kota.",
    ],
  },
  {
    id: 2,
    title: "Acara Hijau Bandung",
    status: "Sedang Berlangsung",
    time: "07.00–10.00 WIB",
    desc: "Penanaman bibit pohon di Bandung dengan relawan lokal.",
    image: "/acara2.jpg",
    location: "Bandung",
    gallery: ["/acara2.jpg", "/acara3.jpg", "/acara4.jpg"],
    team: [
      { name: "Fauzan Ridho", role: "Ketua Relawan" },
      { name: "Alya Rahma", role: "Penyuluh Lingkungan" },
    ],
    benefits: ["Mencegah erosi", "Menambah oksigen", "Kesadaran reboisasi"],
  },
  {
    id: 3,
    title: "Acara Hijau Jakarta",
    status: "Akan Datang",
    time: "08.00–11.00 WIB",
    desc: "Penanaman pohon di Jakarta untuk meningkatkan area hijau kota.",
    image: "/acara3.jpg",
    location: "Jakarta",
    gallery: ["/acara3.jpg", "/acara1.jpg", "/acara4.jpg"],
    team: [
      { name: "Dani Saputra", role: "Koordinator" },
      { name: "Sinta Lestari", role: "Relawan Alam" },
    ],
    benefits: ["Menjaga lingkungan perkotaan", "Mendukung penghijauan"],
  },
  {
    id: 4,
    title: "Acara Hijau Depok",
    status: "Akan Datang",
    time: "09.00–12.00 WIB",
    desc: "Penanaman pohon di Depok bersama komunitas pelestari lingkungan.",
    image: "/acara4.jpg",
    location: "Depok",
    gallery: ["/acara4.jpg", "/acara1.jpg", "/acara2.jpg"],
    team: [
      { name: "Raka Firmansyah", role: "Koordinator Edukasi" },
      { name: "Melisa Utami", role: "Ahli Botani" },
    ],
    benefits: ["Menambah kesadaran masyarakat", "Konservasi tanaman lokal"],
  },
  {
    id: 5,
    title: "Acara Bersih Pantai",
    status: "Sedang Berlangsung",
    time: "06.00–09.00 WIB",
    desc: "Bersih-bersih pantai bersama komunitas pecinta lingkungan.",
    image: "/acara5.jpg",
    location: "Pantai Anyer",
    gallery: ["/acara5.jpg", "/acara2.jpg", "/acara3.jpg"],
    team: [
      { name: "Bayu Pratama", role: "Koordinator Lapangan" },
      { name: "Nina Amalia", role: "Relawan" },
    ],
    benefits: ["Lingkungan pantai bersih", "Meningkatkan kepedulian masyarakat"],
  },
  {
    id: 6,
    title: "Acara Donor Darah",
    status: "Akan Datang",
    time: "10.00–14.00 WIB",
    desc: "Donor darah untuk mendukung stok darah di rumah sakit setempat.",
    image: "/acara6.jpg",
    location: "RSUD Kota",
    gallery: ["/acara6.jpg", "/acara4.jpg", "/acara1.jpg"],
    team: [
      { name: "Hendra Setiawan", role: "Koordinator" },
      { name: "Ria Kusuma", role: "Relawan Medis" },
    ],
    benefits: ["Menyelamatkan nyawa", "Mendukung stok darah nasional"],
  },
  {
    id: 7,
    title: "Acara Edukasi Lingkungan",
    status: "Sedang Berlangsung",
    time: "08.00–11.00 WIB",
    desc: "Edukasi lingkungan untuk anak-anak sekolah dasar.",
    image: "/acara7.jpg",
    location: "Sekolah SD Bogor",
    gallery: ["/acara7.jpg", "/acara3.jpg", "/acara2.jpg"],
    team: [
      { name: "Aulia Rahman", role: "Pengajar" },
      { name: "Fajar Pratama", role: "Relawan Edukasi" },
    ],
    benefits: ["Menumbuhkan kepedulian anak-anak", "Edukasi lingkungan"],
  },
  {
    id: 8,
    title: "Acara Tanam Pohon",
    status: "Akan Datang",
    time: "07.00–10.00 WIB",
    desc: "Penanaman pohon di area terbuka untuk meningkatkan oksigen kota.",
    image: "/acara8.jpg",
    location: "Taman Kota",
    gallery: ["/acara8.jpg", "/acara1.jpg", "/acara2.jpg"],
    team: [
      { name: "Rizki Hidayat", role: "Koordinator Lapangan" },
      { name: "Sari Dewi", role: "Relawan" },
    ],
    benefits: ["Menambah area hijau", "Meningkatkan kualitas udara"],
  },
  {
    id: 9,
    title: "Acara Festival Lingkungan",
    status: "Sedang Berlangsung",
    time: "09.00–17.00 WIB",
    desc: "Festival lingkungan dengan berbagai kegiatan edukasi dan permainan.",
    image: "/acara9.jpg",
    location: "Alun-alun Kota",
    gallery: ["/acara9.jpg", "/acara2.jpg", "/acara4.jpg"],
    team: [
      { name: "Budi Santoso", role: "Ketua Panitia" },
      { name: "Nadia Amalia", role: "Relawan" },
    ],
    benefits: ["Meningkatkan kepedulian masyarakat", "Pendidikan lingkungan"],
  },
  {
    id: 10,
    title: "Acara Workshop Komunitas",
    status: "Akan Datang",
    time: "13.00–16.00 WIB",
    desc: "Workshop komunitas untuk pelatihan kegiatan penghijauan.",
    image: "/acara10.jpg",
    location: "Gedung Komunitas",
    gallery: ["/acara10.jpg", "/acara3.jpg", "/acara1.jpg"],
    team: [
      { name: "Andi Prasetyo", role: "Fasilitator" },
      { name: "Lia Maharani", role: "Relawan" },
    ],
    benefits: ["Edukasi komunitas", "Meningkatkan partisipasi masyarakat"],
  },
];
